"""update client user

Revision ID: 0fe77cacbb6e
Revises: f6c8defb4c6b
Create Date: 2026-04-19 18:09:35.342849

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0fe77cacbb6e'
down_revision: Union[str, Sequence[str], None] = 'f6c8defb4c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_users', 'phone_number')
    # ### end Alembic commands ###
