"""Payment License - transation-reference

Revision ID: 290e24f310fa
Revises: dc2cc55d2c99
Create Date: 2026-05-06 17:30:02.600787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290e24f310fa'
down_revision: Union[str, Sequence[str], None] = 'dc2cc55d2c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_licenses', sa.Column('transaction_reference', sa.String(), nullable=False))
    op.drop_column('payment_licenses', 'transation_reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_licenses', sa.Column('transation_reference', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('payment_licenses', 'transaction_reference')
    # ### end Alembic commands ###
