"""finance - paymentLicense and invoiceLincense

Revision ID: 580c318df6c0
Revises: f40ceb164af7
Create Date: 2026-04-24 20:49:01.066767

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '580c318df6c0'
down_revision: Union[str, Sequence[str], None] = 'f40ceb164af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'invoice_licenses',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('invoice_number', sa.String(), nullable=False),
        sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('issuer_id', sa.UUID(), nullable=True),
        sa.Column('recipient_client_id', sa.UUID(), nullable=True),
        sa.Column('recipient_partner_id', sa.UUID(), nullable=True),
        sa.Column(
            'status',
            sa.Enum('rascunho', 'aberto', 'pago', 'cancelado', 'vencido', name='invoicestatus'),
            nullable=False,
        ),
        sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['issuer_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['recipient_client_id'],
            ['client_profiles.id'],
        ),
        sa.ForeignKeyConstraint(
            ['recipient_partner_id'],
            ['partner_profiles.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_invoice_licenses_invoice_number'),
        'invoice_licenses',
        ['invoice_number'],
        unique=True,
    )
    op.create_table(
        'payment_licenses',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'type',
            sa.Enum('partner_subscription', 'client_license', name='licensetransactiontype'),
            nullable=False,
        ),
        sa.Column('invoice_id', sa.UUID(), nullable=True),
        sa.Column('partner_license_id', sa.UUID(), nullable=True),
        sa.Column('client_license_id', sa.UUID(), nullable=True),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            'status',
            sa.Enum('pendente', 'pago', 'cancelado', 'reembolsado', name='paymentstatus'),
            nullable=False,
        ),
        sa.Column('payment_method', sa.String(), nullable=True),
        sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            '(partner_license_id IS NOT NULL AND client_license_id IS NULL) OR (partner_license_id IS NULL AND client_license_id IS NOT NULL)',
            name='check_payment_license_source',
        ),
        sa.ForeignKeyConstraint(
            ['client_license_id'],
            ['client_licenses.id'],
        ),
        sa.ForeignKeyConstraint(
            ['invoice_id'],
            ['invoice_licenses.id'],
        ),
        sa.ForeignKeyConstraint(
            ['partner_license_id'],
            ['partner_licenses.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_licenses')
    op.drop_index(op.f('ix_invoice_licenses_invoice_number'), table_name='invoice_licenses')
    op.drop_table('invoice_licenses')
    # ### end Alembic commands ###
