"""update license plan_id to better name

Revision ID: a706e408ebfb
Revises: 33e0722ac969
Create Date: 2026-04-19 15:46:45.364962

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a706e408ebfb'
down_revision: Union[str, Sequence[str], None] = '33e0722ac969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_licenses', sa.Column('erp_plan_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('client_licenses_plan_id_fkey'), 'client_licenses', type_='foreignkey')
    op.create_foreign_key(None, 'client_licenses', 'erp_plans', ['erp_plan_id'], ['id'])
    op.drop_column('client_licenses', 'plan_id')
    op.add_column('partner_licenses', sa.Column('partner_plan_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('partner_licenses_plan_id_fkey'), 'partner_licenses', type_='foreignkey')
    op.create_foreign_key(None, 'partner_licenses', 'partner_plans', ['partner_plan_id'], ['id'])
    op.drop_column('partner_licenses', 'plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_licenses', sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'partner_licenses', type_='foreignkey')
    op.create_foreign_key(op.f('partner_licenses_plan_id_fkey'), 'partner_licenses', 'partner_plans', ['plan_id'], ['id'])
    op.drop_column('partner_licenses', 'partner_plan_id')
    op.add_column('client_licenses', sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client_licenses', type_='foreignkey')
    op.create_foreign_key(op.f('client_licenses_plan_id_fkey'), 'client_licenses', 'erp_plans', ['plan_id'], ['id'])
    op.drop_column('client_licenses', 'erp_plan_id')
    # ### end Alembic commands ###
