"""update plan and license

Revision ID: ae01eef068f8
Revises: e2c1de7ed73d
Create Date: 2026-04-18 20:46:13.505551

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ae01eef068f8'
down_revision: Union[str, Sequence[str], None] = 'e2c1de7ed73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_licenses', sa.Column('offline_only', sa.Boolean(), nullable=False))
    op.add_column('client_licenses', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('erp_plans', sa.Column('sync_enabled', sa.Boolean(), nullable=False))
    op.add_column('erp_plans', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('partner_plans', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_plans', 'is_active')
    op.drop_column('erp_plans', 'is_active')
    op.drop_column('erp_plans', 'sync_enabled')
    op.drop_column('client_licenses', 'is_active')
    op.drop_column('client_licenses', 'offline_only')
    # ### end Alembic commands ###
