"""Payment License - transation-reference

Revision ID: dc2cc55d2c99
Revises: 580c318df6c0
Create Date: 2026-05-06 17:28:58.706528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2cc55d2c99'
down_revision: Union[str, Sequence[str], None] = '580c318df6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_licenses', sa.Column('transation_reference', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_licenses', 'transation_reference')
    # ### end Alembic commands ###
