"""optional max_clients in partnerPlan

Revision ID: e1074e0b5e1f
Revises: a706e408ebfb
Create Date: 2026-04-19 15:57:45.510352

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e1074e0b5e1f'
down_revision: Union[str, Sequence[str], None] = 'a706e408ebfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_plans', 'max_clients',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_plans', 'max_clients',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
