"""initial migration

Revision ID: e2c1de7ed73d
Revises:
Create Date: 2026-04-17 20:43:40.690728

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e2c1de7ed73d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'erp_plans',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('default_max_machines', sa.Integer(), nullable=True),
        sa.Column('modules_enabled', sa.JSON(), nullable=False),
        sa.Column('plan_ranges', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'partner_plans',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('max_clients', sa.Integer(), nullable=False),
        sa.Column('allowed_erp_plans', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('username', sa.String(length=20), nullable=True),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column(
            'role',
            sa.Enum('ADMIN', 'PARTNER', 'CLIENT', 'CLIENT_USER', name='userrole'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.Column('pending_email', sa.String(), nullable=True),
        sa.Column('verification_code', sa.String(length=10), nullable=True),
        sa.Column('verification_code_expires', sa.DateTime(timezone=True), nullable=True),
        sa.Column('reset_token', sa.String(length=255), nullable=True),
        sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table(
        'audit_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('actor_id', sa.UUID(), nullable=False),
        sa.Column('action_type', sa.String(), nullable=False),
        sa.Column('target_id', sa.UUID(), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['actor_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'partner_profiles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('company_name', sa.String(), nullable=False),
        sa.Column('nif', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('logo', sa.String(), nullable=True),
        sa.Column('province', sa.String(), nullable=True),
        sa.Column('municipality', sa.String(), nullable=True),
        sa.Column('street', sa.String(), nullable=True),
        sa.Column('neighborhood', sa.String(), nullable=True),
        sa.Column('building', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nif'),
    )
    op.create_table(
        'client_profiles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('partner_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('legal_name', sa.String(), nullable=True),
        sa.Column('nif', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(), nullable=True),
        sa.Column('website', sa.String(), nullable=True),
        sa.Column('regime', sa.String(), nullable=True),
        sa.Column('registration_number', sa.String(), nullable=True),
        sa.Column('logo', sa.String(), nullable=True),
        sa.Column('province', sa.String(), nullable=True),
        sa.Column('municipality', sa.String(), nullable=True),
        sa.Column('street', sa.String(), nullable=True),
        sa.Column('neighborhood', sa.String(), nullable=True),
        sa.Column('building', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['partner_id'],
            ['partner_profiles.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nif'),
        sa.UniqueConstraint('registration_number'),
    )
    op.create_table(
        'partner_licenses',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('partner_id', sa.UUID(), nullable=False),
        sa.Column('plan_id', sa.UUID(), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('expiry_date', sa.DateTime(), nullable=False),
        sa.Column(
            'period',
            sa.Enum('MENSAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL', name='partner_license_periods'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('license_key', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['partner_id'],
            ['partner_profiles.id'],
        ),
        sa.ForeignKeyConstraint(
            ['plan_id'],
            ['partner_plans.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'client_licenses',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('client_id', sa.UUID(), nullable=False),
        sa.Column('partner_id', sa.UUID(), nullable=False),
        sa.Column('plan_id', sa.UUID(), nullable=False),
        sa.Column('authorized_machines', sa.JSON(), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('expiry_date', sa.DateTime(), nullable=False),
        sa.Column(
            'period',
            sa.Enum('MENSAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL', name='client_license_periods'),
            nullable=False,
        ),
        sa.Column('license_key', sa.String(), nullable=True),
        sa.Column('license_metadata', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ['client_id'],
            ['client_profiles.id'],
        ),
        sa.ForeignKeyConstraint(
            ['partner_id'],
            ['partner_profiles.id'],
        ),
        sa.ForeignKeyConstraint(
            ['plan_id'],
            ['erp_plans.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'client_users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('client_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'role_name',
            sa.Enum(
                'ADMIN_LOCAL',
                'GERENTE',
                'CONTABILISTA',
                'TESOUREIRO',
                'FIEL_ARMAZEM',
                'VENDEDOR',
                'CAIXA',
                'GESTOR_RH',
                name='clientuserrole',
            ),
            nullable=False,
        ),
        sa.Column('permissions', sa.JSON(), nullable=False),
        sa.Column('employee_id', sa.String(), nullable=True),
        sa.Column('department', sa.String(), nullable=True),
        sa.Column('phone_extension', sa.String(), nullable=True),
        sa.Column('server_version', sa.Integer(), nullable=False),
        sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['client_id'],
            ['client_profiles.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_users')
    op.drop_table('client_licenses')
    op.drop_table('partner_licenses')
    op.drop_table('client_profiles')
    op.drop_table('partner_profiles')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('partner_plans')
    op.drop_table('erp_plans')
    # ### end Alembic commands ###
