"""add price to erp and partner plan

Revision ID: f40ceb164af7
Revises: 0fe77cacbb6e
Create Date: 2026-04-24 16:33:05.101726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40ceb164af7'
down_revision: Union[str, Sequence[str], None] = '0fe77cacbb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('erp_plans', sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('partner_plans', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_plans', 'price')
    op.drop_column('erp_plans', 'base_price')
    # ### end Alembic commands ###
