"""update enums

Revision ID: f6c8defb4c6b
Revises: e1074e0b5e1f
Create Date: 2026-04-19 16:21:02.138170

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6c8defb4c6b'
down_revision: Union[str, Sequence[str], None] = 'e1074e0b5e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'client_users',
        'role_name',
        existing_type=postgresql.ENUM(
            'ADMIN_LOCAL',
            'GERENTE',
            'CONTABILISTA',
            'TESOUREIRO',
            'FIEL_ARMAZEM',
            'VENDEDOR',
            'CAIXA',
            'GESTOR_RH',
            name='clientuserrole',
        ),
        type_=sa.Enum(
            'admin_local',
            'gerente',
            'contabilista',
            'tesoureiro',
            'fiel_armazem',
            'vendedor',
            'caixa',
            'gestor_rh',
            name='client_user_roles',
        ),
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'role',
        existing_type=postgresql.ENUM('ADMIN', 'PARTNER', 'CLIENT', 'CLIENT_USER', name='userrole'),
        type_=sa.Enum('admin', 'partner', 'client', 'client_user', name='user_roles'),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'role',
        existing_type=sa.Enum('admin', 'partner', 'client', 'client_user', name='user_roles'),
        type_=postgresql.ENUM('ADMIN', 'PARTNER', 'CLIENT', 'CLIENT_USER', name='userrole'),
        existing_nullable=False,
    )
    op.alter_column(
        'client_users',
        'role_name',
        existing_type=sa.Enum(
            'admin_local',
            'gerente',
            'contabilista',
            'tesoureiro',
            'fiel_armazem',
            'vendedor',
            'caixa',
            'gestor_rh',
            name='client_user_roles',
        ),
        type_=postgresql.ENUM(
            'ADMIN_LOCAL',
            'GERENTE',
            'CONTABILISTA',
            'TESOUREIRO',
            'FIEL_ARMAZEM',
            'VENDEDOR',
            'CAIXA',
            'GESTOR_RH',
            name='clientuserrole',
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
